config/routes.rb
Quora::Application.routes.draw do
  root to: 'users#new'

  resources :users do
    resources :questions, :only => [:index]
  end
  resource :session
  resources :questions do
    collection do
      get 'feed'
      get 'popular'
    end
    resources :answers, :only => [:create]
  end

  resources :answers, :only => [:show, :destroy] do
    resources :comments, :only => [:index]
  end

  resources :subjects do
    resources :topics, :only => [:index]
  end

  resources :topics, :only => [:index, :show] do
    collection do
      get 'trending'
    end
    resources :questions, :only => [:index]
  end

  resources :notifications, :only => [:index]

  resources :comments, :only => [:create]
  resources :answer_votes, :only => [:create]
  resources :answer_down_votes, :only => [:create]
  resources :question_followings, :only => [:create, :destroy]
  get 'questions/feed' => 'questions#feed', :as => :feed_questions

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :question_id, :text, :user_id, :votes

  belongs_to :user
  belongs_to :question
  has_many :comments

  validates :text, :presence => true
end

app/models/answer_down_vote.rb
class AnswerDownVote < ActiveRecord::Base
  attr_accessible :answer_id, :user_id
  belongs_to :answer
  belongs_to :user
end

app/models/answer_vote.rb
class AnswerVote < ActiveRecord::Base
  attr_accessible :answer_id, :user_id

  belongs_to :answer
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :answer_id, :text, :user_id

  belongs_to :user
  belongs_to :answer
  has_one :question, through: :answer
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title, :user_id, :votes

  belongs_to :author, class_name: 'User', foreign_key: :user_id
  has_many :post_taggings
  has_many :topics, through: :post_taggings
end

app/models/post_following.rb
class PostFollowing < ActiveRecord::Base
  attr_accessible :post_id, :user_id

  belongs_to :post
  belongs_to :user
end

app/models/post_tagging.rb
class PostTagging < ActiveRecord::Base
  attr_accessible :post_id, :topic_id

  belongs_to :post
  belongs_to :topic
end

app/models/post_vote.rb
class PostVote < ActiveRecord::Base
  attr_accessible :post_id, :user_id

  belongs_to :post
  belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :title, :body, :user_id, :votes, :topic_ids

  has_many :answers
  has_many :comments, through: :answers
  belongs_to :user
  has_many :question_taggings
  has_many :topics, through: :question_taggings
  has_many :question_followings
  has_many :followers, through: :question_followings, source: :user, dependent: :destroy

  validates :title, :presence => true


  def latest_update_time
    latest_update.created_at
  end

  def latest_update
    changes = [self]
    changes << self.answers.last unless self.answers.count == 0
    changes << self.comments.last unless self.comments.count == 0
    last_change = changes.max_by { |change| change.created_at }
    self.last_update = last_change.to_json
    last_change
  end

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  attr_accessible :name

  has_many :topics
  has_many :subject_choices
  has_many :followers, through: :subject_choices, source: :user
end

app/models/subject_choice.rb
class SubjectChoice < ActiveRecord::Base
  attr_accessible :subject_id, :user_id

  belongs_to :subject
  belongs_to :user
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :name, :subject_id

  belongs_to :subject
  has_many :topic_choices
  has_many :followers, through: :topic_choices, source: :user
  has_many :question_taggings
  has_many :questions, through: :question_taggings

  def self.most_popular
    topics = Topic.all :include => [:questions]
    topics.sort_by { |topic| topic.questions.size }.reverse[0..4]
  end
end

app/models/topic_choice.rb
class TopicChoice < ActiveRecord::Base
  attr_accessible :topic_id, :user_id

  belongs_to :topic
  belongs_to :user
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  attr_accessible :blurb, :password, :session_token, :username, :subject_ids

  has_many :questions
  has_many :replies, through: :questions, source: :answers
  has_many :answers
  has_many :answer_comments, through: :answers, source: :comments
  has_many :comments
  has_many :subject_choices
  has_many :topic_choices
  has_many :subjects, through: :subject_choices
  # has_many :topics, through: :topic_choices
  has_many :topics, through: :subjects
  has_many :topical_questions, through: :topics, source: :questions
  has_many :question_followings
  has_many :followed_questions, through: :question_followings, source: :question, dependent: :destroy

  has_many :follower_instances, through: :questions, source: :question_followings



  has_many :posts
  has_many :question_followers, through: :questions, source: :followers
  has_many :answer_votes
  has_many :answer_down_votes
  has_many :answers_voted_on, through: :answer_votes, source: :answer
  has_many :answers_downvoted, through: :answer_down_votes, source: :answer
  has_many :post_votes
  has_many :posts_voted_on, through: :post_votes, source: :post

  validates :username, presence: true, uniqueness: true

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def verify_password(password)
    BCrypt::Password.new(self.password_digest) == password
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @user = current_user
    @topics = Topic.all
    if params.include?(:topic_id)
      @topic = Topic.find(params[:topic_id])
      @questions = @topic.questions
    elsif params.include?(:user_id)
      @params_user = User.find(params[:user_id])
      @questions = @params_user.questions
    else
      @questions = Question.all
    end

    respond_to do |format|
      format.html { render :index }
      format.json { render :json => @questions }
    end
  end

  def create
    @question = current_user.questions.build(params[:question])
    @question.save!
    respond_to do |format|
      format.json { render :json => @question }
    end
  end

  def show
    @user = current_user
    @question = Question.find(params[:id])
    @topics = @question.topics
    @answers = @question.answers.sort_by {|answer| answer.votes}.reverse
  end

  def update
    @question = Question.find(params[:id])
    new_topic_ids = params[:question]
    @question.topic_ids = @question.topic_ids.concat(new_topic_ids)
    @question.save!
    respond_to do |format|
      format.json { render :json => @question }
    end
  end

  def feed
    questions = current_user.questions
    current_user.topical_questions.each do |question|
      questions += [question] unless questions.include?(question)
    end
    current_user.followed_questions.each do |question|
      questions += [question] unless questions.include?(question)
    end
    @questions = questions.sort_by { |question| question.latest_update_time }
    @questions.reverse!
    respond_to do |format|
      format.json { render :json => @questions.to_json(:include => :comments) }
    end
  end

  def popular
    questions = Question.all :include => [:answers, :comments]
    @sorted = questions.sort_by { |q| q.answers.size + q.comments.size }.reverse
    respond_to do |format|
      format.json { render :json => @sorted.to_json(:include => [:comments, :answers])}
    end
  end


end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    return nil unless session[:session_token]
    User.find_by_session_token(session[:session_token])
  end

  def login(user)
    user.session_token = SecureRandom.base64(16)
    user.save
    session[:session_token] = user.session_token
  end

  def logout
    unless logged_in?
      redirect_to new_session_url
      return
    end

    u = current_user
    u.session_token = nil
    u.save
    session[:session_token] = nil
    redirect_to new_session_url
  end

  def logged_in?
    !!current_user
  end

end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/questions/index.html.erb
<% if !@params_user.nil? %>
<h4><%=@user.username%>'s Questions</h4>
<% elsif @topic.nil? %>
<h4>All Questions</h4>
<% else %>
<h4><%=@topic.name%></h4>
<% end %>

<ul>
  <% @questions.each do |question| %>
  <%text = question.answers.count == 1 ? "answer" : "answers"%>
  <%follow_message = @user.followed_questions.include?(question) ? "Unfollow"  : "Follow"%>
  <li>
    <%=link_to question.title, question_url(question)%>
    <%=question.answers.count%> <%=text%>
     <a href="#" class="follow_question" data-id="<%=question.id%>"><%=follow_message%></a>
    <br>
    <%=question.created_at.localtime.strftime('%m/%d/%Y %H:%M')%>

  </li>
  <% end %>
</ul>


<%=link_to "back to user page", user_url(@user)%>
<br>

app/views/questions/show.html.erb
<h4><%=@question.title%></h4>
<h5><%=@question.body%></h5>
<h6>Asked by: <%=@question.user.username%>
<%=@question.created_at.localtime.strftime('%m/%d/%Y %H:%M')%></h6>
<%text = @answers.count == 1 ? "answer" : "answers"%>
<div class="answer_count"><%=@answers.count%> <%=text%></div>
<br>
Tags:
<div class="tag_list">
<% @topics.each do |topic| %>
<%=link_to topic.name, topic_questions_url(topic)%>
<%end%>
</div>
<br>
<a href="#" class="add_topic_link" data-id="<%=@question.id%>">Add Topic</a>
<div class="add_topic"></div>
<br>
<h4>Answers:</h4>

<ul id="answer_list<%=@question.id%>">
  <% @answers.each do |answer| %>
  <% count = answer.comments.count %>
   <%comments_text = count == 1 ? "comment" : "comments"%>
   <%votes_text = answer.votes == 1 ? "vote" : "votes"%>
  <li id="answer_listing<%=answer.id%>">
    <%=answer.text%>
    <a href="#"
      class="comment_count"
      data-id="<%=answer.id%>">
      <span id="count<%=answer.id%>"><%=count%></span>
      <span id="comments_text<%=answer.id%>"><%=comments_text%></span>
    </a>
    <div class="vote count" id="vote_count<%=answer.id%>"><%=answer.votes%>
    <%=votes_text%></div>

    <div class="vote_text" id="vote_text<%=answer.id%>">
    <% if current_user.answers.include?(answer) %>
    <%=''%>
    <% elsif current_user.answers_voted_on.include?(answer)%>
    <%="upvoted"%>
    <% elsif current_user.answers_downvoted.include?(answer)%>
    <%="downvoted"%>
    <% else %>
    <a href="#" class="up_vote" data-id="<%=answer.id%>">+</a>
    <a href="#" class="down_vote" data-id="<%=answer.id%>">-</a>
    <br>
    <% end %>
    </div>
    Posted by: <%=answer.user.username%>

    <% if current_user.answers.include?(answer)%>
      <a href="#" class="delete_answer" data-id="<%=answer.id%>">Remove</a>
    <% end %>
    <br>
    <%=answer.created_at.localtime.strftime('%m/%d/%Y %H:%M')%>
    <br>
    <div id="comments_container<%=answer.id%>"></div>

    <a href="#" class="post_comment" id="post_comment<%=answer.id%>" data-id="<%=answer.id%>">comment</a>
    <div id="comment_field<%=answer.id%>"></div>
  </li>
  <% end %>
  </ul>

  <a href="#" class="answer_question" id="answer_question<%=@question.id%>" data-id="<%=@question.id%>">Add Answer</a>
  <div id="question_box<%=@question.id%>"></div>

<%=link_to "back to user page", user_url(@user)%>
<br>
<%=link_to "all questions", questions_url%>
<br>


<script type="text/javascript">
$(function() {
  $(".add_topic_link").on("click", function(event) {
    var id = $(this).attr("data-id");
    console.log(id)
    event.preventDefault();
    toggleMessage(this, "Add Topic", "cancel")
    $.ajax({
      url: "/topics.json",
      type: "get",
      success: function(topicsData) {
        if ($(".add_topic").html() === "") {
          var selectTopic = JST["templates/topic_select_existing"]({topics: topicsData})
          $(".add_topic").html(selectTopic);
        }
        else {
          $(".add_topic").html("");
        }
        $(".submit_topic").on("click", function(event) {
          event.preventDefault();
          var topicId = [parseInt($(".topic_select").val())];
            $.ajax({
              url:"/questions/" + id + ".json",
              type: "put",
              data: {question: topicId},
              success: function(questionData) {
               $(".add_topic").html("");
               $(".add_topic_link").html("Add Topic");
              }
            });
          });
      }
    });
  });
});
</script>