config/routes.rb
Quora::Application.routes.draw do
  root to: 'users#new'

  resources :users do
    resources :questions, :only => [:index]
  end
  resource :session
  resources :questions do
    collection do
      get 'feed'
      get 'popular'
    end
    resources :answers, :only => [:create]
  end

  resources :answers, :only => [:show, :destroy] do
    resources :comments, :only => [:index]
  end

  resources :subjects do
    resources :topics, :only => [:index]
  end

  resources :topics, :only => [:index, :show] do
    collection do
      get 'trending'
    end
    resources :questions, :only => [:index]
  end

  resources :notifications, :only => [:index]

  resources :comments, :only => [:create]
  resources :answer_votes, :only => [:create]
  resources :answer_down_votes, :only => [:create]
  resources :question_followings, :only => [:create, :destroy]
  get 'questions/feed' => 'questions#feed', :as => :feed_questions

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :question_id, :text, :user_id, :votes

  belongs_to :user
  belongs_to :question
  has_many :comments

  validates :text, :presence => true
end

app/models/answer_down_vote.rb
class AnswerDownVote < ActiveRecord::Base
  attr_accessible :answer_id, :user_id
  belongs_to :answer
  belongs_to :user
end

app/models/answer_vote.rb
class AnswerVote < ActiveRecord::Base
  attr_accessible :answer_id, :user_id

  belongs_to :answer
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :answer_id, :text, :user_id

  belongs_to :user
  belongs_to :answer
  has_one :question, through: :answer
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title, :user_id, :votes

  belongs_to :author, class_name: 'User', foreign_key: :user_id
  has_many :post_taggings
  has_many :topics, through: :post_taggings
end

app/models/post_following.rb
class PostFollowing < ActiveRecord::Base
  attr_accessible :post_id, :user_id

  belongs_to :post
  belongs_to :user
end

app/models/post_tagging.rb
class PostTagging < ActiveRecord::Base
  attr_accessible :post_id, :topic_id

  belongs_to :post
  belongs_to :topic
end

app/models/post_vote.rb
class PostVote < ActiveRecord::Base
  attr_accessible :post_id, :user_id

  belongs_to :post
  belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :title, :body, :user_id, :votes, :topic_ids

  has_many :answers
  has_many :comments, through: :answers
  belongs_to :user
  has_many :question_taggings
  has_many :topics, through: :question_taggings
  has_many :question_followings
  has_many :followers, through: :question_followings, source: :user, dependent: :destroy

  validates :title, :presence => true


  def latest_update_time
    latest_update.created_at
  end

  def latest_update
    changes = [self]
    changes << self.answers.last unless self.answers.count == 0
    changes << self.comments.last unless self.comments.count == 0
    last_change = changes.max_by { |change| change.created_at }
    self.last_update = last_change.to_json
    last_change
  end

end

app/models/question_tagging.rb
class QuestionTagging < ActiveRecord::Base
  attr_accessible :question_id, :topic_id

  belongs_to :question
  belongs_to :topic
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  attr_accessible :name

  has_many :topics
  has_many :subject_choices
  has_many :followers, through: :subject_choices, source: :user
end

app/models/subject_choice.rb
class SubjectChoice < ActiveRecord::Base
  attr_accessible :subject_id, :user_id

  belongs_to :subject
  belongs_to :user
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :name, :subject_id

  belongs_to :subject
  has_many :topic_choices
  has_many :followers, through: :topic_choices, source: :user
  has_many :question_taggings
  has_many :questions, through: :question_taggings

  def self.most_popular
    topics = Topic.all :include => [:questions]
    topics.sort_by { |topic| topic.questions.size }.reverse[0..4]
  end
end

app/models/topic_choice.rb
class TopicChoice < ActiveRecord::Base
  attr_accessible :topic_id, :user_id

  belongs_to :topic
  belongs_to :user
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  attr_accessible :blurb, :password, :session_token, :username, :subject_ids

  has_many :questions
  has_many :replies, through: :questions, source: :answers
  has_many :answers
  has_many :answer_comments, through: :answers, source: :comments
  has_many :comments
  has_many :subject_choices
  has_many :topic_choices
  has_many :subjects, through: :subject_choices
  # has_many :topics, through: :topic_choices
  has_many :topics, through: :subjects
  has_many :topical_questions, through: :topics, source: :questions
  has_many :question_followings
  has_many :followed_questions, through: :question_followings, source: :question, dependent: :destroy

  has_many :follower_instances, through: :questions, source: :question_followings



  has_many :posts
  has_many :question_followers, through: :questions, source: :followers
  has_many :answer_votes
  has_many :answer_down_votes
  has_many :answers_voted_on, through: :answer_votes, source: :answer
  has_many :answers_downvoted, through: :answer_down_votes, source: :answer
  has_many :post_votes
  has_many :posts_voted_on, through: :post_votes, source: :post

  validates :username, presence: true, uniqueness: true

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def verify_password(password)
    BCrypt::Password.new(self.password_digest) == password
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @subjects = Subject.all
    @user = User.new
    render :new
  end

  def create
    @user = User.new(params[:user])
    if @user.save!
      login(@user)
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    unless @user === current_user
      redirect_to new_session_url
      return
    end
    @subjects = @user.subjects
    render :show
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    return nil unless session[:session_token]
    User.find_by_session_token(session[:session_token])
  end

  def login(user)
    user.session_token = SecureRandom.base64(16)
    user.save
    session[:session_token] = user.session_token
  end

  def logout
    unless logged_in?
      redirect_to new_session_url
      return
    end

    u = current_user
    u.session_token = nil
    u.save
    session[:session_token] = nil
    redirect_to new_session_url
  end

  def logged_in?
    !!current_user
  end

end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<form action="<%= users_url %>" method="post">

  <h4>Choose some subjects you're interested in</h4>
  <ul>
    <% @subjects.each do |subject| %>
    <li><input
          type="checkbox"
          name="user[subject_ids][]"
          value="<%=subject.id%>"
          id="subject_id">
        <label for="subject_id"><%=subject.name%></label>
        </li>
        <% end %>
        <br>


  <label for="user_username">Username</label>
  <input type="text" name="user[username]" id="user_username">

  <label for="user_password">Password</label>
  <input type="password" name="user[password]" id="user_password">

  <input type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
<div class="sidebar">

<h3>User page</h3>
<%= @user.username %>
<br>
<a href="#" class="new_question_link">Ask a Question</a>
<br>
<div class="question"></div>
<%=link_to "Notifications", notifications_url, :method => :get%>

<h4>Subjects Following</h4>
<div class="subjects_following"></div>
<ul>
  <% @subjects.each do |subject| %>
  <li><%=subject.name%>
    <br>
  <a href="#" class="show_topics" id="show_topics<%=subject.id%>" data-id="<%=subject.id%>">View Topics</a>
  <div id="topic_list<%=subject.id%>"></div>
  </li>
  <% end %>
  </ul>



<h4>Trending Topics</h4>
<div class="trending"></div>

<a href="/users/<%=@user.id%>/questions">My Questions</a>
<br>

<%=link_to "All Questions", questions_url, :method => :get%>


</div>



<div class="feed">
  <div style="clear: both">
<a href="#" class="get_most_recent"><h5 class="selected" style="float: left">Most Recent</h5></a>
<a href="#" class="get_most_popular"><h5 style="float: left" class="get_most_popular">Popular</h5></a>
  </div>
  <hr />
<div class="feed_questions"></div>
<ul>
</ul>
</div>



<script type="text/javascript">
$(function() {
  getFeed();
  toggle = "recent";
  getTrendingTopics();
  $(".get_most_recent").on("click", function(event) {
    $(this).find('h5').addClass('selected')
    $(".get_most_popular").find('h5').removeClass('selected');
    toggle = "recent";
    event.preventDefault
    getFeed();
  });
  $(".get_most_popular").on("click", function(event) {
    $(".get_most_recent").find('h5').removeClass('selected');
    $(this).find('h5').addClass('selected');
    toggle = "popular";
    event.preventDefault;
    getPopular();
  })
  setInterval(function() {
    toggle === "popular" ? getPopular() : getFeed();
    getTrendingTopics();
  }, 60 * 1000);
});
</script>