config/routes.rb
Quora::Application.routes.draw do
  root to: 'users#new'

  resources :users do
    resources :questions, :only => [:index]
  end
  resource :session
  resources :questions do
    collection do
      get 'feed'
      get 'popular'
    end
    resources :answers, :only => [:create]
  end

  resources :answers, :only => [:show, :destroy] do
    resources :comments, :only => [:index]
  end

  resources :subjects do
    resources :topics, :only => [:index]
  end

  resources :topics, :only => [:index, :show] do
    collection do
      get 'trending'
    end
    resources :questions, :only => [:index]
  end

  resources :notifications, :only => [:index]

  resources :comments, :only => [:create]
  resources :answer_votes, :only => [:create]
  resources :answer_down_votes, :only => [:create]
  resources :question_followings, :only => [:create, :destroy]
  get 'questions/feed' => 'questions#feed', :as => :feed_questions

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :question_id, :text, :user_id, :votes

  belongs_to :user
  belongs_to :question
  has_many :comments

  validates :text, :presence => true
end

app/models/answer_vote.rb
class AnswerVote < ActiveRecord::Base
  attr_accessible :answer_id, :user_id

  belongs_to :answer
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :answer_id, :text, :user_id

  belongs_to :user
  belongs_to :answer
  has_one :question, through: :answer
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title, :user_id, :votes

  belongs_to :author, class_name: 'User', foreign_key: :user_id
  has_many :post_taggings
  has_many :topics, through: :post_taggings
end

app/models/post_following.rb
class PostFollowing < ActiveRecord::Base
  attr_accessible :post_id, :user_id

  belongs_to :post
  belongs_to :user
end

app/models/post_tagging.rb
class PostTagging < ActiveRecord::Base
  attr_accessible :post_id, :topic_id

  belongs_to :post
  belongs_to :topic
end

app/models/post_vote.rb
class PostVote < ActiveRecord::Base
  attr_accessible :post_id, :user_id

  belongs_to :post
  belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :title, :body, :user_id, :votes, :topic_ids

  has_many :answers
  has_many :comments, through: :answers
  belongs_to :user
  has_many :question_taggings
  has_many :topics, through: :question_taggings
  has_many :question_followings
  has_many :followers, through: :question_followings, source: :user, dependent: :destroy

  validates :title, :presence => true


  def latest_update_time
    latest_update.created_at
  end

  def latest_update
    changes = [self]
    changes << self.answers.last unless self.answers.count == 0
    changes << self.comments.last unless self.comments.count == 0
    last_change = changes.max_by { |change| change.created_at }
    self.last_update = last_change.to_json
    last_change
  end

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  attr_accessible :name

  has_many :topics
  has_many :subject_choices
  has_many :followers, through: :subject_choices, source: :user
end

app/models/subject_choice.rb
class SubjectChoice < ActiveRecord::Base
  attr_accessible :subject_id, :user_id

  belongs_to :subject
  belongs_to :user
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :name, :subject_id

  belongs_to :subject
  has_many :topic_choices
  has_many :followers, through: :topic_choices, source: :user
  has_many :question_taggings
  has_many :questions, through: :question_taggings

  def self.most_popular
    topics = Topic.all :include => [:questions]
    topics.sort_by { |topic| topic.questions.size }.reverse[0..4]
  end
end

app/models/topic_choice.rb
class TopicChoice < ActiveRecord::Base
  attr_accessible :topic_id, :user_id

  belongs_to :topic
  belongs_to :user
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  attr_accessible :blurb, :password, :session_token, :username, :subject_ids

  has_many :questions
  has_many :replies, through: :questions, source: :answers
  has_many :answers
  has_many :answer_comments, through: :answers, source: :comments
  has_many :comments
  has_many :subject_choices
  has_many :topic_choices
  has_many :subjects, through: :subject_choices
  # has_many :topics, through: :topic_choices
  has_many :topics, through: :subjects
  has_many :topical_questions, through: :topics, source: :questions
  has_many :question_followings
  has_many :followed_questions, through: :question_followings, source: :question, dependent: :destroy

  has_many :follower_instances, through: :questions, source: :question_followings



  has_many :posts
  has_many :question_followers, through: :questions, source: :followers
  has_many :answer_votes
  has_many :answer_down_votes
  has_many :answers_voted_on, through: :answer_votes, source: :answer
  has_many :answers_downvoted, through: :answer_down_votes, source: :answer
  has_many :post_votes
  has_many :posts_voted_on, through: :post_votes, source: :post

  validates :username, presence: true, uniqueness: true

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def verify_password(password)
    BCrypt::Password.new(self.password_digest) == password
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    return nil unless session[:session_token]
    User.find_by_session_token(session[:session_token])
  end

  def login(user)
    user.session_token = SecureRandom.base64(16)
    user.save
    session[:session_token] = user.session_token
  end

  def logout
    unless logged_in?
      redirect_to new_session_url
      return
    end

    u = current_user
    u.session_token = nil
    u.save
    session[:session_token] = nil
    redirect_to new_session_url
  end

  def logged_in?
    !!current_user
  end

end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.erb
<% if logged_in? %>
<%= link_to "Home", user_url(current_user), :class => 'brand' %>
<% end %>

<ul class="nav">
  <% if logged_in? %>
    <li>
    <%= link_to('Logout', session_url, :method =>'delete') %>
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_session_url)  %>
    </li>
  <% end %>
  <% if logged_in? %>

  <% else %>
    <li>
    <%= link_to('Sign up', new_user_url)  %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "quora" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
              <%if logged_in?%>
              logged in as <%= current_user.username%>
              <%end%>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>